# spring.profiles.active を明示的に指定しないと使われる設定ファイル。
# デプロイ用 WAR 内ではこの値が使われるので、本番環境向けの設定を記載する。

spring:
  # 本番環境の DB 接続情報
  # 環境変数かアプリ起動時の引数で接続情報を指定する。
  # https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/htmlsingle/#howto-use-short-command-line-arguments
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/exampledb}
    username: ${DB_USER:exampleuser}
    password: ${DB_PASS:examplepass}

server:
  port: ${PORT:8081}
